In [1]:
import numpy as np
#from numpy import linalg as LA

In [2]:
# https://github.com/dalek7/Algorithms/blob/master/Rotation/Coplanarity/COPLANAR_042314_140602.txt
Q = [0.71, -0.12, 0.69,
 -0.09, -0.99, -0.08,
 -0.70, 0.00, 0.72]

In [3]:
Q = [0.36, 0.48, -0.8,
    -0.8, 0.6, 0,
    0.48, 0.64, 0.6]

In [4]:
theta = np.radians(30)
s = np.sin(theta)
c = np.cos(theta)

Q = [c, -s, 0, 
     s, c, 0, 
     0, 0, 1]

In [5]:
theta

0.5235987755982988

In [6]:
Q = np.array(Q)

In [7]:
Q = Q.reshape((3,3))

In [8]:
Q

array([[ 0.8660254, -0.5      ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [9]:
w, v = np.linalg.eig(Q)

w: The eigenvalues, each repeated according to its multiplicity.
The eigenvalues are not necessarily ordered. The resulting array will be of complex type, unless the imaginary part is zero in which case it will be cast to a real type. 

In [10]:
w

array([0.8660254+0.5j, 0.8660254-0.5j, 1.       +0.j ])

In [11]:
w[2]

(1+0j)

First, one of the roots (or eigenvalues) is 1, which tells us that some direction is unaffected by the matrix. 
For rotations in three dimensions, this is the axis of the rotation (a concept that has no meaning in any other dimension).

In [12]:
v

array([[0.70710678+0.j        , 0.70710678-0.j        ,
        0.        +0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j,
        0.        +0.j        ],
       [0.        +0.j        , 0.        -0.j        ,
        1.        +0.j        ]])

Second, the other two roots are a pair of complex conjugates, whose product is 1 (the constant term of the quadratic), and whose sum is $2 cos\theta$ (the negated linear term). 
This factorization is of interest for 3 × 3 rotation matrices because the same thing occurs for all of them. (As special cases, for a null rotation the "complex conjugates" are both 1, and for a 180° rotation they are both −1.)

In [13]:
w[0] * w[1] # --> 1

(1+0j)

In [14]:
w[0] + w[1] # --> 2 cos θ

(1.7320508075688774+0j)

In [15]:
np.arccos((w[0] + w[1] )/2)

(0.5235987755982987-0j)

In [16]:
theta

0.5235987755982988

In [18]:
np.degrees(np.real(np.arccos((w[0] + w[1] )/2)))

29.999999999999993

In [19]:
np.degrees(theta)

29.999999999999996

* https://en.wikipedia.org/wiki/Rotation_matrix#Decompositions